{% set name = "dateparser" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dateparser-{{ version }}.tar.gz
  sha256: e703db1815270c020552f4b3e3a981937b48b2cbcfcef5347071b74788dd9214

build:
  entry_points:
    - dateparser-download = dateparser_cli.cli:entrance
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-dateutil
    - pytz
    - regex !=2019.02.19,!=2021.8.27
    - tzlocal

test:
  requires:
    - pip
  commands:
    - pip check
    - dateparser-download --help
  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
