{% set version = "1.1.0" %}

package:
  name: dateparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateparser/dateparser-{{ version }}.tar.gz
  sha256: faa2b97f51f3b5ff1ba2f17be90de2b733fb6191f89b4058787473e8202f3044

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dateparser-download = dateparser_cli.cli:entrance

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - python-dateutil
    - pytz
    - regex !=2019.02.19,!=2021.8.27
    - tzlocal

test:
  requires:
    - pip
  commands:
    - pip check
    - dateparser-download --help
  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
