{% set version = "0.7.2" %}

package:
  name: dateparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateparser/dateparser-{{ version }}.tar.gz
  sha256: e1eac8ef28de69a554d5fcdb60b172d526d61924b1a40afbbb08df459a36006b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - pytz
    - regex
    - tzlocal

test:
  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Date parsing library designed to parse dates from HTML pages.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
