{% set version = "0.7.4" %}

package:
  name: dateparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateparser/dateparser-{{ version }}.tar.gz
  sha256: fb5bfde4795fa4b179fe05c2c25b3981f785de26bec37e247dee1079c63d5689

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - pytz
    - regex !=2019.02.19
    - tzlocal

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages.

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
