{% set version = "0.6.0" %}

package:
  name: dateparser
  version: {{ version }}

source:
  fn: dateparser-{{ version }}.tar.gz
  url: https://github.com/scrapinghub/dateparser/archive/v{{ version }}.tar.gz
  sha256: eec38d4036b7174d9ade2801c0a437f2af107fbfb69814791bbc42ac9ccb5918

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - python-dateutil
    - ruamel.yaml
    - jdatetime
    - umalqurra
    - pytz
    - regex
    - tzlocal
    - convertdate

test:
  imports:
    - data
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Date parsing library designed to parse dates from HTML pages.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
