travis:
  secure:
    BINSTAR_TOKEN: feWNWAaZbgt2ATl1VbK9nZg5G317LBei4GA3lOLXFBah3L+6idnWDW/2crdUZdOMIh9QD5JkViU6MeA4m3qUTpUGJYPJcknrB0NG8fLkbI6pH/Nsbwf0Uc2rhK5q8+PW0SjbMtkxIJN7eqS41Pz+MUN3LtN3DLR2ausQXWmWxXzpJU+/2gOGYbDSb+FteqsPyJl3DA3HkakhhTXVt+pB+Njje+azMMm9pIL9qE8NVW0SaTN4dIr2SB5DAyHzO3zcEe9IP9Ioq4NcEUR3W9AAjFJk5ZXlFryTBr/HEW/nDhSOR/Btd9tTyKSTiiXPeA/5ARE8AcONSYZF6CLixOpI5yVZ3/yde5RWAkKhdj+ZAyEtEdtQVHBtRNOURNrr6iygR1InrvQJQlnjy+Y5PH+C35ZBxlYH7QYUoeRfgTwbuleYRHWsUOnjHnnsed8UNM2gzwdElIxxfz/s1WUptP9NFKrcfQC1gQ2OL2LFHmWBYjN3p/BQ/K6RfCelg7ngkqPmaoWSh/ZzeEHM5p6+mDwmXPWEIq1Ia+k8s9QbgMYFAGNGwT8cI2uhoRLIetYdcmX5wpGtJJQ1jWwOh4aKPn/BU5ybplkZ+i9cEos21bdzGmVvbI4hhPPgNBYvO9+ztKCsZUQexpK/7sdaxNnB8+WCGsERFAt8F54ppF7XKMyHIXk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
